# Generated by Django 4.2.2 on 2023-06-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('edible', models.BooleanField()),
            ],
        ),
    ]
