# Generated by Django 4.2.2 on 2023-06-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('date', models.DateField(verbose_name='Date Found')),
                ('description', models.TextField(max_length=200)),
                ('shroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shroom')),
            ],
        ),
    ]
