# Generated by Django 4.2.2 on 2023-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_specimenorigin_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='shroom',
            name='meals',
            field=models.ManyToManyField(to='main_app.meal'),
        ),
    ]
